#!/bin/sh 

# This is the fan-fix script turned into a simple service for TrueNAS (BSD)
# After placing this script at: /usr/local/etc/rc.d/fan_fix
# Run 'service fan_fix enable; service fan_fix start` 

. /etc/rc.subr 

name="fan_fix" 
start_cmd="${name}_start" 
stop_cmd=":" 

fan_fix_start() 
{
	/usr/local/bin/ipmitool sensor thresh FAN2 lower 0 100 200
  /usr/local/bin/ipmitool sensor thresh FAN4 lower 0 100 200
}

load_rc_config $name 
run_rc_command "$1" 
