#!/bin/sh

# Applies to Supermicro motherboards
# ISSUE: Fans continuously ramp up to 100% and back down in a loop
# RCA: Fan operational speeds are below expected RPM limits
# FIX: Change the IPMI sensor thresholds

# This is a simple bash script that will update the thresholds for 2 fans and can be run on startup
# It will allow you to run in fan modes other than "FULL SPEED"

/usr/bin/ipmitool sensor thresh FAN2 lower 0 100 200
/usr/bin/ipmitool sensor thresh FAN4 lower 0 100 200
